name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 0 * * 1,4'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -i -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/quick-handler" -H "apikey:${{ secrets.SUPABASE_KEY }}" -H "Authorization:Bearer ${{ secrets.SUPABASE_KEY }}"
