name: Prevent Supabase Inactivity
on:
  schedule:
    - cron: '0 0 * * 1,4'
  workflow_dispatch:
jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping main project
        run: curl -i -X POST "https://gotdehypsbkbyrasdbrr.supabase.co/rest/v1/rpc/ping" -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" || true
      - name: Ping secondary project
        run: curl -i -X POST "https://jgcibolwmwotsymhgtjr.supabase.co/rest/v1/rpc/ping" -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" || true
